/* =========================================================
   Impariamo! — Kleinwörter für die Wort-Info
   Häufige Wörter aus den Beispielsätzen, die NICHT als eigener
   Eintrag im Wortschatz stehen (Artikel, Präpositionen, gebeugte
   Formen, Mehrzahl …). Kuratiert → haben Vorrang vor Wortschatz
   und Verbformen. Nur Daten; Logik in glossar.js.
   ========================================================= */

/* Artikel, die vor Wortschatz-Einträgen stehen („la mela" → Schlüssel „mela") */
const ARTIKEL = {
  it: ["il", "lo", "la", "l'", "i", "gli", "le", "un", "uno", "una", "un'"],
  en: ["the", "a", "an", "to"],
  es: ["el", "la", "los", "las", "un", "una", "unos", "unas"],
  fr: ["le", "la", "l'", "les", "un", "une", "des", "se", "s'"],
  pt: ["o", "a", "os", "as", "um", "uma", "uns", "umas"]
};

const KLEINWOERTER = {
  it: {
    "il": "der", "lo": "der / ihn", "la": "die / sie", "i": "die (Pl.)", "gli": "die (Pl.) / ihm",
    "le": "die (Pl.) / ihr", "un": "ein", "uno": "ein / eins", "una": "eine",
    "di": "von", "a": "zu / nach / in", "da": "von / seit / bei", "in": "in", "con": "mit",
    "su": "auf / über", "per": "für / um zu", "tra": "zwischen / in (zeitlich)", "fra": "zwischen / in (zeitlich)",
    "del": "des / vom", "della": "der / von der", "dello": "des / vom", "dei": "der (Pl.) / einige",
    "degli": "der (Pl.) / von den", "delle": "der (Pl.) / von den",
    "al": "zum / am", "allo": "zum / an den", "alla": "zur / an der", "ai": "an den / zu den",
    "alle": "an den / um (Uhrzeit)", "dal": "vom / seit", "nel": "im", "nella": "in der",
    "nei": "in den", "nelle": "in den", "sul": "auf dem", "sulla": "auf der / über die",
    "sui": "auf den / über die", "col": "mit dem", "ad": "zu / an (vor Vokal)",
    "e": "und", "ed": "und", "o": "oder", "ma": "aber", "che": "dass / der, die, das / was",
    "se": "wenn / ob", "non": "nicht", "sì": "ja", "no": "nein",
    "è": "ist", "ha": "hat", "ho": "ich habe", "sono": "ich bin / sie sind", "si": "sich / man",
    "mi": "mich / mir", "ti": "dich / dir", "ci": "uns / da", "vi": "euch", "ne": "davon",
    "io": "ich", "tu": "du", "lui": "er", "lei": "sie / Sie", "noi": "wir / uns",
    "me": "mich / mir", "te": "dich / dir",
    "mio": "mein", "mia": "meine", "miei": "meine (Pl.)", "mie": "meine (Pl.)",
    "suo": "sein / ihr", "sua": "seine / ihre", "suoi": "seine / ihre (Pl.)",
    "questo": "dieser / dieses", "questa": "diese", "quella": "jene / die dort",
    "quest'anno": "dieses Jahr", "dov'è": "wo ist",
    "ogni": "jede(r/s)", "più": "mehr / am meisten", "dopo": "nach / danach", "sempre": "immer",
    "anni": "Jahre", "tutto": "alles / ganz", "senza": "ohne", "stato": "gewesen / Staat",
    "prima": "vorher / zuerst / erste", "tempo": "Zeit / Wetter", "molti": "viele",
    "molto": "sehr / viel", "tutti": "alle", "città": "Stadt", "bene": "gut",
    "solo": "nur / allein", "fatto": "gemacht / Tatsache", "ancora": "noch / wieder",
    "stata": "gewesen", "giorni": "Tage", "ora": "jetzt / Stunde", "anche": "auch",
    "parte": "Teil / fährt ab", "favore": "Gefallen (per favore = bitte)", "vita": "Leben",
    "giorno": "Tag", "fino": "bis", "lungo": "lang / entlang", "richiede": "erfordert",
    "po'": "(un po') ein bisschen", "po": "(un po') ein bisschen", "nuovo": "neu",
    "acqua": "Wasser", "subito": "sofort", "qui": "hier", "euro": "Euro", "fine": "Ende",
    "anno": "Jahr", "ore": "Stunden / Uhr", "sera": "Abend", "molte": "viele",
    "azienda": "Firma / Betrieb", "sotto": "unter", "professionale": "beruflich / professionell",
    "costa": "kostet / Küste", "centro": "Zentrum", "caldo": "warm / Hitze",
    "fuori": "draußen / außerhalb", "ormai": "inzwischen", "paese": "Land / Dorf",
    "ufficio": "Büro", "proprio": "eigen / wirklich, gerade", "punto": "Punkt", "mai": "nie",
    "perso": "verloren", "spese": "Ausgaben / Einkäufe", "pubblico": "öffentlich / Publikum",
    "senso": "Sinn", "progetto": "Projekt", "bisogna": "man muss", "passo": "Schritt",
    "buon": "gut(en)", "giornata": "Tag (Verlauf)", "così": "so", "digitale": "digital",
    "niente": "nichts", "preferisco": "ich bevorzuge / lieber", "stasera": "heute Abend",
    "rapporto": "Beziehung / Bericht", "resta": "bleibt", "durante": "während",
    "portato": "gebracht", "vero": "wahr / echt", "grande": "groß", "forte": "stark",
    "famiglia": "Familie", "cerco": "ich suche", "servono": "man braucht / sie dienen",
    "locale": "lokal / Lokal", "vera": "wahr / echt", "online": "online", "troppo": "zu (viel)",
    "nuove": "neue", "riduce": "reduziert", "nuova": "neue", "preso": "genommen",
    "dura": "dauert / hart", "minuti": "Minuten", "testo": "Text", "caso": "Fall / Zufall",
    "lascia": "lässt", "dati": "Daten", "tutte": "alle", "merito": "Verdienst",
    "italiano": "italienisch / Italiener", "pressione": "Druck", "superato": "überwunden / bestanden",
    "serve": "man braucht / dient", "arte": "Kunst", "finalmente": "endlich", "fondo": "Grund / Boden",
    "mesi": "Monate", "nuovi": "neue", "messo": "gelegt / gestellt", "mattina": "Morgen / Vormittag",
    "viaggio": "Reise", "alta": "hoch", "male": "schlecht / weh", "piace": "gefällt",
    "giusto": "richtig", "propria": "eigene", "tempi": "Zeiten", "problema": "Problem",
    "rischio": "Risiko", "perfetto": "perfekt", "culturale": "kulturell",
    "abito": "ich wohne / Kleid", "numero": "Nummer / Zahl", "esperienza": "Erfahrung",
    "clienti": "Kunden", "costi": "Kosten", "campione": "Champion / Probe",
    "lasciato": "gelassen / verlassen", "poco": "wenig", "opera": "Werk / Oper",
    "accordo": "Einverständnis / Abkommen", "appena": "gerade erst / sobald", "storico": "historisch",
    "rete": "Netz", "intera": "ganz", "fatica": "Mühe", "domanda": "Frage / Nachfrage",
    "ragazzo": "Junge", "cambia": "ändert (sich)", "conviene": "es lohnt sich",
    "controllo": "Kontrolle", "ultimi": "letzte", "colori": "Farben", "presentato": "vorgestellt",
    "davanti": "vor / vorne", "luce": "Licht", "finito": "fertig / beendet", "natura": "Natur",
    "cielo": "Himmel", "amici": "Freunde", "bar": "Bar / Café", "profondo": "tief",
    "piccole": "kleine", "pochi": "wenige", "paziente": "geduldig / Patient",
    "stampa": "Presse / Druck", "sociale": "sozial", "presto": "früh / bald", "tanti": "viele",
    "fretta": "Eile", "roma": "Rom", "economia": "Wirtschaft", "rispetto": "Respekt / im Vergleich",
    "arrivato": "angekommen", "voti": "Noten / Stimmen", "andato": "gegangen", "bella": "schön",
    "olio": "Öl", "mal": "Schmerz / schlecht", "cena": "Abendessen", "altro": "andere(r) / noch etwas",
    "campagna": "Land (ländlich) / Kampagne", "deciso": "entschieden", "rende": "macht / gibt zurück",
    "chiesto": "gefragt", "cura": "Pflege / Behandlung", "punta": "Spitze / zielt",
    "contro": "gegen", "ecco": "hier ist / da", "compro": "ich kaufe", "pieno": "voll",
    "comunità": "Gemeinschaft", "routine": "Routine", "spesso": "oft",
    "alba": "Morgendämmerung", "prossima": "nächste", "posto": "Platz / Ort", "mani": "Hände",
    "tira": "zieht", "memoria": "Gedächtnis / Erinnerung", "diventato": "geworden",
    "sistema": "System", "malattia": "Krankheit", "notte": "Nacht",
    "porto": "Hafen / ich bringe", "moda": "Mode", "pagare": "bezahlen",
    "come": "wie", "dove": "wo", "quando": "wann / wenn", "perché": "warum / weil",
    "cosa": "was / Sache", "chi": "wer", "quanto": "wie viel"
  },

  en: {
    "the": "der / die / das", "a": "ein(e)", "an": "ein(e)", "is": "ist", "are": "sind",
    "was": "war", "were": "waren", "be": "sein", "been": "gewesen", "has": "hat",
    "have": "haben", "had": "hatte", "do": "tun / machen", "does": "tut / macht",
    "did": "tat / machte", "don't": "nicht (tun)", "can": "können", "can't": "kann nicht",
    "will": "werden", "would": "würde", "should": "sollte", "it": "es", "you": "du / Sie / ihr",
    "my": "mein(e)", "your": "dein(e) / Ihr(e)", "this": "dies(e)", "that": "das / dass",
    "so": "so / also", "or": "oder", "what": "was", "where": "wo", "when": "wann / wenn",
    "why": "warum", "about": "über / ungefähr",
    "to": "zu / nach / um zu", "of": "von", "i": "ich", "in": "in", "he": "er", "for": "für",
    "on": "auf / an", "with": "mit", "and": "und", "at": "an / bei / um", "we": "wir",
    "his": "sein(e)", "by": "von / bis / neben", "as": "als / wie", "from": "von / aus",
    "up": "hoch / auf", "out": "aus / hinaus", "every": "jede(r/s)", "me": "mich / mir",
    "i'm": "ich bin", "after": "nach", "she": "sie", "all": "alle / ganz", "not": "nicht",
    "time": "Zeit / Mal", "always": "immer", "they": "sie (Pl.)", "into": "in … hinein",
    "there": "dort / da", "years": "Jahre", "him": "ihn / ihm", "off": "weg / aus",
    "over": "über / vorbei", "good": "gut", "new": "neu", "without": "ohne",
    "get": "bekommen / werden", "before": "vor / bevor", "now": "jetzt", "but": "aber",
    "her": "sie / ihr(e)", "no": "nein / kein", "it's": "es ist", "day": "Tag", "more": "mehr",
    "year": "Jahr", "how": "wie", "here": "hier", "just": "nur / gerade", "its": "sein(e) (von es)",
    "very": "sehr", "most": "die meisten / am meisten", "morning": "Morgen", "still": "noch / still",
    "days": "Tage", "through": "durch", "i'll": "ich werde", "city": "Stadt", "too": "auch / zu",
    "going": "gehend (going to = werden)", "well": "gut / nun", "make": "machen", "only": "nur",
    "between": "zwischen", "us": "uns", "love": "Liebe / lieben", "public": "öffentlich / Öffentlichkeit",
    "evening": "Abend", "need": "brauchen", "down": "hinunter / unten", "costs": "Kosten / kostet",
    "long": "lang", "end": "Ende", "i've": "ich habe", "against": "gegen", "way": "Weg / Art",
    "social": "sozial", "thank": "danken", "our": "unser(e)", "who": "wer / der, die (Relativ)",
    "put": "legen / stellen", "let's": "lass uns", "among": "unter / zwischen",
    "last": "letzte(r) / dauern", "decided": "entschieden", "makes": "macht",
    "people": "Leute / Menschen", "hard": "hart / schwer", "few": "wenige", "everyone": "jeder / alle",
    "got": "bekommen / geworden", "little": "klein / wenig", "small": "klein",
    "keep": "behalten / weiter…", "left": "links / verlassen / übrig", "set": "gesetzt / Set",
    "life": "Leben", "night": "Nacht", "home": "Zuhause / nach Hause", "family": "Familie",
    "use": "benutzen", "let": "lassen", "away": "weg", "next": "nächste(r)",
    "best": "beste(r) / am besten", "leave": "verlassen / gehen", "hours": "Stunden",
    "once": "einmal / sobald", "everything": "alles", "them": "sie / ihnen", "than": "als (Vergleich)",
    "pay": "bezahlen", "old": "alt", "working": "arbeitend / Arbeit", "entire": "ganz",
    "euros": "Euro", "even": "sogar / selbst", "never": "nie", "feel": "fühlen",
    "break": "Pause / brechen", "one's": "sein(e) (man)", "free": "frei / kostenlos",
    "enough": "genug", "digital": "digital", "project": "Projekt", "under": "unter",
    "i'd": "ich würde / ich hatte", "turn": "drehen / an der Reihe sein", "felt": "fühlte / gefühlt",
    "during": "während", "requires": "erfordert", "play": "spielen", "nature": "Natur",
    "deep": "tief", "case": "Fall", "if": "wenn / ob", "warm": "warm", "number": "Nummer / Zahl",
    "professional": "beruflich / professionell", "towards": "in Richtung / gegenüber",
    "dish": "Gericht / Schale", "prefer": "bevorzugen", "online": "online", "easy": "leicht",
    "live": "leben / live", "lost": "verloren", "whole": "ganz", "remains": "bleibt",
    "town": "Stadt", "summer": "Sommer", "become": "werden", "seems": "scheint",
    "yet": "noch / jedoch", "managed": "geschafft / geleitet", "news": "Nachrichten",
    "patient": "geduldig / Patient", "sorry": "Entschuldigung", "again": "wieder",
    "there's": "es gibt / da ist", "thanks": "danke", "italian": "italienisch", "centre": "Zentrum",
    "per": "pro", "round": "rund / Runde", "tend": "neigen (zu)", "together": "zusammen",
    "seemed": "schien", "moment": "Moment", "made": "gemacht", "service": "Dienst / Service",
    "each": "jede(r/s)", "excellent": "ausgezeichnet", "own": "eigen", "area": "Gebiet / Bereich",
    "look": "schauen / Aussehen", "far": "weit", "report": "Bericht", "early": "früh",
    "lot": "Menge (a lot = viel)", "oneself": "sich (selbst)", "heat": "Hitze", "weather": "Wetter",
    "bring": "bringen", "until": "bis", "great": "großartig / groß", "tell": "erzählen / sagen",
    "story": "Geschichte", "matter": "Angelegenheit / wichtig sein", "yes": "ja",
    "cultural": "kulturell", "power": "Macht / Strom", "meet": "treffen", "experience": "Erfahrung",
    "essential": "wesentlich", "he's": "er ist", "fresh": "frisch", "cent": "Cent",
    "think": "denken", "balance": "Gleichgewicht", "order": "Bestellung / Ordnung",
    "won": "gewonnen", "local": "lokal / örtlich", "turns": "dreht / wird", "young": "jung",
    "possible": "möglich", "chose": "wählte", "passed": "vergangen / bestanden", "months": "Monate",
    "straight": "gerade / direkt", "travel": "reisen", "often": "oft", "reduces": "reduziert",
    "brought": "gebracht", "high": "hoch", "works": "funktioniert / arbeitet", "system": "System",
    "really": "wirklich", "short": "kurz", "sense": "Sinn", "needed": "gebraucht",
    "times": "Zeiten / Mal", "colour": "Farbe", "since": "seit", "within": "innerhalb",
    "something": "etwas", "problem": "Problem"
  },

  es: {
    "el": "der", "la": "die / sie", "los": "die (Pl.)", "las": "die (Pl.)", "un": "ein",
    "una": "eine", "de": "von", "a": "zu / nach / an", "en": "in / auf", "con": "mit",
    "por": "durch / für / wegen", "para": "für / um zu", "es": "ist", "está": "ist (Zustand)",
    "son": "sind", "no": "nein / nicht", "me": "mich / mir", "te": "dich / dir",
    "mi": "mein(e)", "tu": "dein(e)", "su": "sein(e) / ihr(e)", "este": "dieser",
    "esta": "diese", "como": "wie / ich esse",
    "del": "des / vom", "se": "sich / man", "que": "dass / der, die, das / was", "y": "und",
    "al": "zum / dem", "ha": "hat", "lo": "es / ihn / das", "más": "mehr", "todo": "alles / ganz",
    "he": "ich habe", "sin": "ohne", "cada": "jede(r/s)", "siempre": "immer", "años": "Jahre",
    "desde": "seit / von", "entre": "zwischen", "tiempo": "Zeit / Wetter", "tras": "nach",
    "fue": "war / ging", "bien": "gut", "pero": "aber", "sobre": "über / auf", "hasta": "bis",
    "ya": "schon", "muchos": "viele", "han": "haben", "antes": "vorher / vor", "todos": "alle",
    "sus": "seine / ihre", "noche": "Nacht / Abend", "días": "Tage", "año": "Jahr", "muy": "sehr",
    "poco": "wenig", "día": "Tag", "durante": "während", "muchas": "viele", "ciudad": "Stadt",
    "toda": "ganz / jede", "favor": "Gefallen (por favor = bitte)", "esa": "diese / jene",
    "fin": "Ende", "aquí": "hier", "mucho": "viel", "nada": "nichts", "vida": "Leben",
    "mis": "meine", "horas": "Stunden", "después": "danach / nach", "paso": "Schritt / ich verbringe",
    "nuevo": "neu", "buen": "gut", "profesional": "beruflich / professionell", "cuesta": "kostet",
    "menos": "weniger", "hecho": "gemacht / Tatsache", "largo": "lang", "deja": "lässt",
    "euros": "Euro", "falta": "Fehlen / es fehlt", "fuera": "draußen / außerhalb",
    "sigue": "folgt / macht weiter", "parte": "Teil", "yo": "ich", "digital": "digital",
    "punto": "Punkt", "nunca": "nie", "hora": "Stunde / Uhrzeit", "público": "öffentlich / Publikum",
    "sí": "ja", "momento": "Moment", "todas": "alle", "gran": "groß(artig)",
    "estado": "Zustand / Staat / gewesen", "si": "wenn / ob", "hacia": "in Richtung",
    "siendo": "seiend", "mal": "schlecht", "llevo": "ich trage / bringe", "mismo": "selbst / gleich",
    "final": "Ende / letzte", "proyecto": "Projekt", "riesgo": "Risiko", "caso": "Fall",
    "ante": "vor / angesichts", "relación": "Beziehung", "laboral": "Arbeits-", "forma": "Form / Art",
    "local": "lokal", "prefiero": "ich bevorzuge / lieber", "todavía": "noch", "vez": "Mal",
    "antiguo": "alt / ehemalig", "reduce": "reduziert", "nueva": "neue", "enseguida": "sofort",
    "pueblo": "Dorf / Volk", "él": "er", "cualquier": "irgendein / jeder beliebige",
    "perfecto": "perfekt", "fondo": "Grund / Boden", "bajo": "unter / niedrig",
    "campo": "Feld / Land", "centro": "Zentrum", "hemos": "wir haben", "atención": "Aufmerksamkeit",
    "último": "letzte(r)", "alto": "hoch", "demasiado": "zu (viel)", "gastos": "Ausgaben",
    "lleva": "trägt / dauert", "alta": "hoch", "requiere": "erfordert", "cuando": "wenn / als",
    "pone": "legt / stellt", "lugar": "Ort", "acuerdo": "Einverständnis / Abkommen",
    "llegar": "ankommen", "exige": "verlangt", "quien": "wer / der, die", "número": "Nummer / Zahl",
    "fuerte": "stark", "también": "auch", "ciento": "hundert (por ciento = Prozent)",
    "pasado": "vergangen / Vergangenheit", "crecido": "gewachsen", "queda": "bleibt / es gibt noch",
    "obra": "Werk", "ahora": "jetzt", "perdido": "verloren", "meses": "Monate", "nuevas": "neue",
    "verano": "Sommer", "viaje": "Reise", "puso": "legte / stellte", "gusta": "gefällt",
    "cuidado": "Vorsicht / Pflege", "cambia": "ändert (sich)", "colores": "Farben",
    "sentido": "Sinn", "luz": "Licht", "redes": "Netze / soziale Netzwerke", "problema": "Problem",
    "minutos": "Minuten", "pasa": "passiert / vergeht", "tarde": "Nachmittag / spät",
    "cielo": "Himmel", "aquella": "jene", "causa": "Ursache", "cultural": "kulturell",
    "fiscal": "steuerlich", "social": "sozial", "texto": "Text", "aún": "noch", "buenos": "gute",
    "noches": "Nächte (buenas noches = gute Nacht)", "así": "so", "experiencia": "Erfahrung",
    "varios": "mehrere", "familiar": "familiär / Familien-", "puesto": "Stelle / gestellt",
    "costes": "Kosten", "incluso": "sogar", "contra": "gegen", "familia": "Familie", "ella": "sie",
    "calor": "Hitze / Wärme", "obras": "Werke / Baustellen", "buena": "gute", "red": "Netz",
    "nuevos": "neue", "hizo": "machte", "prefiere": "bevorzugt", "primer": "erste(r)",
    "control": "Kontrolle", "propia": "eigene", "ritmo": "Rhythmus", "paciente": "geduldig / Patient",
    "presentó": "stellte vor", "país": "Land", "poder": "Macht / können",
    "investigación": "Forschung", "buenas": "gute", "mucha": "viel(e)", "ti": "dich / dir",
    "espera": "wartet / Warten", "italiano": "italienisch", "economía": "Wirtschaft",
    "presión": "Druck", "superado": "überwunden", "o": "oder", "valor": "Wert / Mut",
    "salsa": "Soße", "joven": "jung", "algo": "etwas", "aceite": "Öl", "cena": "Abendessen",
    "servicio": "Service / Dienst", "excelente": "ausgezeichnet", "arte": "Kunst",
    "común": "gemeinsam / üblich", "vive": "lebt", "patrimonio": "Erbe / Vermögen", "abre": "öffnet",
    "jardín": "Garten", "comunidad": "Gemeinschaft", "confianza": "Vertrauen", "zona": "Zone / Gebiet",
    "compro": "ich kaufe", "sentía": "fühlte", "rutina": "Routine", "despacio": "langsam",
    "rápido": "schnell", "sirven": "dienen / man braucht", "llega": "kommt an",
    "personal": "persönlich / Personal", "memoria": "Gedächtnis", "dura": "dauert / hart",
    "notablemente": "deutlich", "sistema": "System", "masa": "Teig / Masse",
    "conviene": "es lohnt sich", "tan": "so", "duras": "harte", "enfermedad": "Krankheit",
    "color": "Farbe", "moda": "Mode", "pagar": "bezahlen", "artículo": "Artikel", "tiempos": "Zeiten",
    "dónde": "wo", "qué": "was", "cómo": "wie", "porque": "weil", "por qué": "warum"
  },

  fr: {
    "le": "der / ihn", "la": "die / sie", "les": "die (Pl.)", "un": "ein", "une": "eine",
    "des": "einige / der (Pl.)", "de": "von", "à": "zu / nach / in", "en": "in / davon",
    "dans": "in", "pour": "für / um zu", "est": "ist", "c'est": "das ist", "ce": "dies / das",
    "cette": "diese", "mon": "mein", "ma": "meine", "mes": "meine (Pl.)", "ton": "dein",
    "sa": "sein(e) / ihr(e)", "leur": "ihr", "y": "dort / dahin",
    "a": "hat", "je": "ich", "il": "er / es", "du": "vom / des / etwas", "au": "zum / am / im",
    "et": "und", "ai": "(ich) habe", "avec": "mit", "sur": "auf / über", "nous": "wir / uns",
    "pas": "nicht (ne … pas)", "ne": "(ne … pas) nicht", "se": "sich", "par": "durch / pro / von",
    "plus": "mehr / nicht mehr", "que": "dass / was / als", "tout": "alles / ganz",
    "fait": "gemacht / macht / Tatsache", "ont": "haben", "me": "mich / mir",
    "suis": "(ich) bin / folge", "son": "sein(e) / Klang", "elle": "sie", "on": "man / wir",
    "été": "gewesen / Sommer", "vous": "ihr / Sie", "après": "nach", "sont": "sind",
    "qui": "wer / der, die, das", "chaque": "jede(r/s)", "tu": "du", "bien": "gut", "sans": "ohne",
    "toujours": "immer", "aux": "zu den / an den", "ils": "sie (Pl.)", "ses": "seine / ihre",
    "temps": "Zeit / Wetter", "depuis": "seit", "comme": "wie / als", "beaucoup": "viel",
    "peu": "wenig", "heures": "Stunden / Uhr", "entre": "zwischen", "mais": "aber",
    "toute": "ganz / jede", "très": "sehr", "avant": "vor / vorher", "ça": "das", "vie": "Leben",
    "fais": "(ich/du) mache(st)", "années": "Jahre", "faut": "(il faut) man muss", "tous": "alle",
    "jours": "Tage", "encore": "noch / wieder", "avons": "(wir) haben", "était": "war",
    "pendant": "während", "mal": "schlecht / weh", "ville": "Stadt", "doit": "muss",
    "soir": "Abend", "te": "dich / dir", "reste": "bleibt / Rest", "ans": "Jahre", "année": "Jahr",
    "même": "selbst / sogar / gleich", "eau": "Wasser", "plaît": "gefällt (s'il vous plaît = bitte)",
    "entreprise": "Unternehmen", "sous": "unter", "passe": "verbringt / geht vorbei", "fin": "Ende",
    "prends": "(ich/du) nehme / nimmst", "ici": "hier", "feu": "Feuer / Ampel", "réduit": "reduziert",
    "nombreuses": "zahlreiche", "rien": "nichts", "travaille": "arbeitet", "compte": "Konto / zählt",
    "voudrais": "(ich) möchte", "véritable": "wahr / echt", "jour": "Tag", "non": "nein / nicht",
    "long": "lang", "peut": "kann", "où": "wo / wohin", "va": "geht", "chez": "bei",
    "toutes": "alle", "dois": "(ich/du) muss(t)", "grande": "groß", "vais": "(ich) gehe / werde",
    "nouveau": "neu", "euros": "Euro", "bon": "gut", "suite": "Folge / Fortsetzung", "jamais": "nie",
    "trop": "zu (viel)", "sens": "Sinn / Richtung", "matin": "Morgen", "demande": "Frage / fragt",
    "nuit": "Nacht", "monde": "Welt / Leute", "peux": "(ich/du) kann(st)", "contre": "gegen",
    "plat": "Gericht / flach", "préfère": "bevorzuge", "désormais": "von nun an",
    "arrive": "kommt an / passiert", "état": "Zustand / Staat", "moi": "ich / mir / mich",
    "journée": "Tag (Verlauf)", "si": "wenn / ob / so", "augmenté": "erhöht", "eu": "gehabt",
    "nouvelles": "neue / Nachrichten", "partie": "Teil / Partie", "quand": "wann / wenn",
    "aime": "liebt / mag", "projet": "Projekt", "mis": "gelegt / gestellt",
    "est-ce": "(est-ce que) Fragewort", "quelques": "einige", "bonne": "gute", "presse": "Presse",
    "sommes": "(wir) sind", "exige": "verlangt", "quel": "welche(r)", "équipe": "Team / Mannschaft",
    "centre": "Zentrum", "chaud": "warm / heiß", "ligne": "Linie / Leitung", "change": "ändert (sich)",
    "mieux": "besser", "moins": "weniger", "certains": "manche / einige",
    "passé": "vergangen / Vergangenheit", "jusqu'à": "bis", "numérique": "digital",
    "coup": "Schlag / Mal", "comment": "wie", "parfait": "perfekt", "point": "Punkt",
    "petite": "kleine", "fois": "Mal", "coûte": "kostet", "frais": "frisch / Kosten",
    "attention": "Achtung / Aufmerksamkeit", "seul": "allein / einzig", "offre": "Angebot / bietet",
    "salle": "Saal / Raum", "fond": "Grund / Hintergrund", "perdu": "verloren", "doux": "sanft / süß",
    "pays": "Land", "problème": "Problem", "réseaux": "Netze / soziale Netzwerke", "nature": "Natur",
    "texte": "Text", "oui": "ja", "votre": "Ihr(e) / euer", "fut": "war", "cela": "das",
    "devant": "vor", "toi": "du / dich / dir", "expérience": "Erfahrung",
    "personne": "Person / niemand", "parcours": "Weg / Laufbahn",
    "professionnel": "beruflich / professionell", "cherche": "sucht", "donne": "gibt",
    "rapport": "Bericht / Beziehung", "art": "Kunst", "mise": "Einsatz / Setzen", "enfin": "endlich",
    "personnes": "Personen", "historique": "historisch", "public": "öffentlich / Publikum",
    "voyage": "Reise", "soi": "sich", "école": "Schule", "as": "(du) hast", "bout": "Ende / Stück",
    "cause": "Ursache", "minutes": "Minuten", "village": "Dorf", "ciel": "Himmel",
    "rendu": "zurückgegeben / gemacht", "nombreux": "zahlreich", "dit": "gesagt / sagt",
    "jeunes": "junge / Jugendliche", "pouvoir": "können / Macht", "examen": "Prüfung",
    "prendre": "nehmen", "parle": "spricht", "es": "(du) bist", "poste": "Stelle / Post",
    "fort": "stark", "parmi": "unter (mehreren)", "professionnelle": "beruflich",
    "écoute": "hört zu", "entretien": "Gespräch / Pflege", "aussi": "auch", "dernier": "letzte(r)",
    "coûts": "Kosten", "valeur": "Wert", "campagne": "Land (ländlich) / Kampagne",
    "famille": "Familie", "siècle": "Jahrhundert", "ouvre": "öffnet", "cher": "teuer / lieb",
    "confiance": "Vertrauen", "tant": "so viel", "pris": "genommen", "appel": "Anruf / Aufruf",
    "lentement": "langsam", "souvent": "oft", "formation": "Ausbildung", "contrôle": "Kontrolle",
    "mode": "Mode / Art", "dernières": "letzte", "couleurs": "Farben", "achat": "Kauf",
    "essaie": "versucht", "devons": "(wir) müssen", "moment": "Moment", "raison": "Grund / Recht",
    "l'": "der / die / das", "d'": "von", "j'": "ich", "c'": "das", "qu'": "dass / was",
    "n'": "(ne … pas) nicht", "s'": "sich", "m'": "mich / mir", "t'": "dich / dir"
  },

  pt: {
    "o": "der / ihn", "a": "die / zu", "os": "die (Pl.)", "as": "die (Pl.)", "um": "ein",
    "uma": "eine", "de": "von", "em": "in", "com": "mit", "por": "durch / für",
    "para": "für / nach / um zu", "é": "ist", "está": "ist (Zustand)", "são": "sind",
    "não": "nein / nicht", "eu": "ich", "você": "du / Sie", "meu": "mein", "minha": "meine",
    "que": "dass / was / der, die, das", "como": "wie", "quando": "wann / wenn", "onde": "wo",
    "do": "des / vom", "da": "der / von der", "no": "im / auf dem", "na": "in der / auf der",
    "e": "und", "ao": "zum / dem", "à": "zur / der", "dos": "der (Pl.) / von den", "mais": "mehr",
    "das": "der (Pl.) / von den", "sem": "ohne", "anos": "Jahre", "muito": "sehr / viel",
    "sempre": "immer", "depois": "danach / nach", "todos": "alle", "se": "sich / wenn / ob",
    "entre": "zwischen", "bem": "gut", "dia": "Tag", "às": "um (Uhrzeit) / zu den",
    "tempo": "Zeit / Wetter", "noite": "Nacht / Abend", "mas": "aber", "sua": "seine / ihre",
    "esta": "diese", "até": "bis / sogar", "muitos": "viele", "pelo": "durch den / für den",
    "cada": "jede(r/s)", "já": "schon", "antes": "vorher / vor", "seu": "sein / ihr",
    "nas": "in den", "tudo": "alles", "durante": "während", "bom": "gut",
    "favor": "Gefallen (por favor = bitte)", "aquela": "jene", "muitas": "viele",
    "pela": "durch die / für die", "ainda": "noch", "fim": "Ende", "sobre": "über",
    "cidade": "Stadt", "pouco": "wenig", "todo": "ganz / alles", "dias": "Tage", "ele": "er",
    "só": "nur / allein", "preciso": "ich brauche / präzise", "qualquer": "irgendein / jede(r) beliebige",
    "numa": "in einer", "horas": "Stunden", "aqui": "hier", "fica": "bleibt / liegt", "ano": "Jahr",
    "todas": "alle", "mesmo": "selbst / sogar / gleich", "aos": "zu den", "vida": "Leben",
    "profissional": "beruflich / professionell", "num": "in einem", "parte": "Teil",
    "nada": "nichts", "mal": "schlecht / kaum", "exige": "verlangt", "longo": "lang",
    "grande": "groß", "novo": "neu", "toda": "ganz / jede", "vez": "Mal", "nunca": "nie",
    "causa": "Ursache", "euros": "Euro", "fora": "draußen / außerhalb", "centro": "Zentrum",
    "relação": "Beziehung", "manhã": "Morgen", "gosto": "ich mag / Geschmack",
    "suas": "seine / ihre (Pl.)", "digital": "digital", "ponto": "Punkt",
    "pelos": "durch die / für die (Pl.)", "custa": "kostet", "novas": "neue", "projeto": "Projekt",
    "ela": "sie", "passo": "Schritt", "sociais": "soziale", "caso": "Fall", "deixa": "lässt",
    "após": "nach", "boa": "gute", "prefiro": "ich bevorzuge / lieber", "verdadeira": "wahr / echt",
    "meses": "Monate", "desde": "seit", "vezes": "Male", "redes": "Netze / soziale Netzwerke",
    "doente": "krank", "estado": "Zustand / Staat / gewesen", "minhas": "meine (Pl.)",
    "forte": "stark", "quente": "warm / heiß", "online": "online", "obra": "Werk / Baustelle",
    "família": "Familie", "guarda": "bewahrt / Wache", "duas": "zwei", "compra": "Kauf / kauft",
    "cuidado": "Vorsicht / Pflege", "frente": "Vorderseite (em frente = vor)", "reduz": "reduziert",
    "público": "öffentlich / Publikum", "nova": "neue", "muda": "ändert (sich)",
    "seus": "seine / ihre (Pl.)", "risco": "Risiko", "continua": "geht weiter / bleibt",
    "menos": "weniger", "sim": "ja", "meus": "meine (Pl.)", "sala": "Raum / Wohnzimmer",
    "também": "auch", "cento": "hundert (por cento = Prozent)", "custos": "Kosten",
    "forma": "Form / Art", "baixo": "niedrig / unter", "certo": "richtig / sicher", "contra": "gegen",
    "falta": "Mangel / fehlt", "arte": "Kunst", "dele": "sein (von ihm)", "campo": "Feld / Land",
    "difícil": "schwierig", "finalmente": "endlich", "fundo": "Grund / Boden", "calor": "Hitze / Wärme",
    "demasiado": "zu (viel)", "despesas": "Ausgaben", "viagem": "Reise", "rotina": "Routine",
    "cor": "Farbe", "sistema": "System", "cores": "Farben", "minutos": "Minuten",
    "passa": "verbringt / vergeht", "poucos": "wenige", "cultural": "kulturell", "semanas": "Wochen",
    "trabalhadores": "Arbeiter", "apresentou": "stellte vor", "social": "sozial",
    "poder": "Macht / können", "texto": "Text", "assim": "so", "perante": "vor / angesichts",
    "número": "Nummer / Zahl", "confiança": "Vertrauen", "gestão": "Verwaltung / Management",
    "sob": "unter", "percurso": "Weg / Strecke", "tirar": "nehmen / ziehen",
    "passado": "vergangen / Vergangenheit", "excesso": "Übermaß", "dar": "geben",
    "local": "lokal / Ort", "final": "Ende / letzte", "jornal": "Zeitung", "agora": "jetzt",
    "antigo": "alt / ehemalig", "câmara": "Kammer / Rathaus", "histórico": "historisch",
    "públicos": "öffentliche", "alta": "hoch", "chega": "kommt an / reicht", "leva": "bringt / dauert",
    "anda": "geht / läuft", "sentido": "Sinn / Richtung", "telemóvel": "Handy",
    "verdadeiro": "wahr / echt", "luz": "Licht", "problema": "Problem", "aldeia": "Dorf",
    "natureza": "Natur", "cima": "oben (em cima = auf)", "momento": "Moment", "ti": "dich / dir",
    "razão": "Grund / Recht", "naquele": "in jenem", "narrativa": "Erzählung", "verdade": "Wahrheit",
    "perfeito": "perfekt", "alguns": "einige", "país": "Land", "investigação": "Forschung",
    "tarde": "Nachmittag / spät", "si": "sich", "falar": "sprechen", "italiano": "italienisch",
    "partir": "aufbrechen (a partir de = ab)", "vários": "mehrere", "economia": "Wirtschaft",
    "familiar": "familiär / Familien-", "pôr": "legen / stellen", "partido": "kaputt / Partei",
    "valor": "Wert", "ordem": "Ordnung / Befehl", "atenção": "Aufmerksamkeit",
    "época": "Zeit / Epoche", "molho": "Soße", "azeite": "Olivenöl", "jantar": "Abendessen",
    "ou": "oder", "conquistou": "eroberte / gewann", "comum": "gemeinsam / üblich", "alto": "hoch",
    "século": "Jahrhundert", "perdi": "ich verlor", "ponta": "Spitze", "uso": "Gebrauch",
    "nosso": "unser", "rede": "Netz", "compro": "ich kaufe", "turismo": "Tourismus",
    "tornou-se": "wurde", "devagar": "langsam", "próxima": "nächste", "servem": "dienen / man braucht"
  }
};
